apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-curl
  namespace: default
spec:
  nodeSelector:
    nodegroup: my-nodegroup
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/bash", "-c", "sleep infinity"]
    stdin: true
    tty: true
    securityContext:
      privileged: true # 필요시 설정
  restartPolicy: Never

