apiVersion: v1
kind: Service
metadata:
  name: service-prometheus
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: practice-prometheus
    app.kubernetes.io/component: server
  ports:
  - port: 80
    targetPort: 9090
    protocol: TCP
  type: NodePort
